### ISSUE TITLE
Any way to make this work with select2?

### ISSUE THREAD

**Issue by zelenij** [djibe/material#10]
This is a great piece of work, my web site looks very material!  One thing is missing - there are no searchable select box options.  A third party plugin for JQery exists, but it doesn't play nice with this whole setup.  Any ideas on how to fix it? https://select2.org/ - the resulting selects show up as "regular" bootstrap ones (or even plain ones, can't really tell).  Kinda breaks the whole visual consistency of my forms...

**Comment by justlevine** [comment]
What specifically is the problem? Select2 works fine on my install...

**Comment by zelenij** [comment]
Well, the ones with select2 look different.  Here is a screenshot for illustration - there are two selects side by side, the one on the left is unmodified, the one on the right is with select2.  Note the rounded appearance of the frame etc.

![image](https://user-images.githubusercontent.com/5512551/85238526-14157780-b461-11ea-8b89-c0c9a19ae380.png)

**Comment by justlevine** [comment]
Ahh so its not that select2 doesnt work, its that it has its own css styles?
Try googling select2 material themes and you should find a bunch of 3rd-party css files. 
Based on your screenshot this one seems like itl fit [https://codepen.io/rpuga/pen/Baypwpr](https://codepen.io/rpuga/pen/Baypwpr)

**Comment by zelenij** [comment]
Well, I tried that, and I found the same link you shared.  However, the end result was kinda ugly and not matching what you can see in codepen.  I suspect it might be clashing with material design UI.  Obviously, this probably can be debugged, but I was wondering if this is something other people have already figured out.

**Comment by tbuyle** [comment]
I use Select2 with Material (Daemonite version) with some CSS and it works ok. 

Here is a GIST with my sccs : https://gist.github.com/tbuyle/4b6aa8c2fe7dfaea1103c0f7eb76fc1c

It's certainly not 100% perfect but it does the trick for me.

**Comment by zelenij** [comment]
@tbuyle I tried compiling your scss to CSS using a command line tool, but it failed :)

**Comment by tbuyle** [comment]
This SCSS depends on variables from Bootstrap and material and can not be compiled alone.

**Comment by djibe** [comment]
I'm working on it

**Comment by djibe** [comment]
Working on the default one.
![default](https://user-images.githubusercontent.com/13089414/85459857-f18b7780-b5a2-11ea-97f0-0440d51acee8.gif)

you will be able to set: theme: 'outlined' for this
![outlined](https://user-images.githubusercontent.com/13089414/85459850-efc1b400-b5a2-11ea-9f62-bea880cfbfb4.gif)

I have to do:

- [X] Merge Select2 + Select2 Bootstrap4 + djibe SCSS sources for lighter theme
- [X] Default theme
- [X] Outlined theme
- [X] Filled theme
- [X] Line ripple
- [X] Disabled
- [X] Searchbox and results
- [X] Fix optgroup
- [X] Multiple select + select icon animation
- [X] Validated form
- [X] Dropdown above
- [ ] Merge WIP in Daemonite Material
- [ ] Documentation for plugins (ionRangeSlider, Maxlength, Select2, Autosize for now)

**Comment by zelenij** [comment]
Thanks! I knew it wasn't trivial :)

**Comment by djibe** [comment]
Hi @zelenij , here is a first version : https://gist.github.com/djibe/2f394a3c7e7eb2510a801cce976ad6f1
Standalone (don't import any Select2 css file).
Don't set a theme or set it to 'outlined'

Optgroup is bugged
Searchbox is ugly

**Comment by djibe** [comment]
Hi, I updated Gist with default, or theme 'outlined' and theme 'filled'.
Can you test it ?

**Comment by zelenij** [comment]
Thank you @djibe, will give it a go and update

**Comment by zelenij** [comment]
To be honest, I don't see much difference - the only thing, select drop down looks more material:

![image](https://user-images.githubusercontent.com/5512551/86353061-4e6ce900-bc99-11ea-8940-4b37c289e034.png)

I copied your gist into a css file and linked it to my site, I presume this is how it is supposed to be used? 

Select2@4.1.0-beta.1 .  Also tried 4.0.13, but actually looks ugly :)

**Comment by djibe** [comment]
Hi, don't import any other Select2 css.
Use latest Select2.
Set theme: 'outlined' (or 'filled')
I updated Gist right now.

I'm nearly done with multiple select.

**Comment by zelenij** [comment]
I think it's better, but with filled theme the multi-select looks kinda dodgy:

![image](https://user-images.githubusercontent.com/5512551/86357618-afe48600-bca0-11ea-99fe-2df3b4fe5efb.png)

**Comment by djibe** [comment]
I'm not done with Multiple version.

**Comment by djibe** [comment]
@zelenij 
Think I got it. See my gist.
$(".js-example-basic-single").select2({
          theme: "filled",
          placeholder: 'Fruit',
          width: '300px',
          multiple: true,
          // minimumResultsForSearch: Infinity /* Hide search on single */
        });

Select2 width has to be set with JS.

For a simple single select, I use a minimum 200px width that don't have to be manually set.
Tell me if you experience bugs.

**Comment by zelenij** [comment]
Visually looks better! I think there is a bug however:

![image](https://user-images.githubusercontent.com/5512551/86418926-5746d480-bd04-11ea-8070-cceb0c9785a2.png)

I select the first item from the drop down. If I close the drop down it is not shown in the main area:

![image](https://user-images.githubusercontent.com/5512551/86418971-84938280-bd04-11ea-95aa-5828397c4b50.png)

Selecting other items seems to work, so it is not consistent.  Nothing in the error console.

If I switch to vanilla select2, it works as expected:

![image](https://user-images.githubusercontent.com/5512551/86419033-b1479a00-bd04-11ea-8e0b-8e30f821effa.png)

**Comment by djibe** [comment]
True.
This is because I tested with a placeholder (so a first blank option).
i'll try to fix it tonight.

**Comment by djibe** [comment]
@zelenij 
Updated gist.
Hope it is final version :D 
Is it good for you ?

**Comment by djibe** [comment]
@zelenij Hi, is the latest Gist update good for you ?

**Comment by zelenij** [comment]
@djibe - sorry for not coming back earlier, was dealing with unrelated stuff.  Looks fine now, thanks.  Is there a way to control the height of the multi-select box? See how a single and multi-select ones differ here?

![image](https://user-images.githubusercontent.com/5512551/87221140-4d743f80-c39c-11ea-978c-2d5860f26d47.png)

**Comment by djibe** [comment]
Hi @zelenij 
Normaly the filled theme is 56px height.
I updated gist.
You may try again.

**Comment by zelenij** [comment]
I don't see any difference to be honest.  And looking at the latest commit in the gist, I see that the only change is the background image.  Maybe you didn't push the rest of it? :)

**Comment by djibe** [comment]
You can use material-plugins.css to style select2.
Set theme to "", "filled" or "outlined".
Doc is on the way

**Comment by djibe** [comment]
Hi.
You can use material-plugins.css from the dist folder and use Select2 as usual (don't set a theme, or set 'filled' or 'outlined')

**Comment by zelenij** [comment]
Thanks, will give it a try

**Comment by djibe** [comment]
Here it is: https://djibe.github.io/material/docs/4.5/plugins/select-select2/
