### ISSUE TITLE
utilities/ripple.scss missing. 

### ISSUE THREAD

**Issue by justlevine** [djibe/material#11]
Seems in the last commit to [_utilities.scss](https://github.com/djibe/material/blob/master/assets/scss/_utilities.scss), you added a reference to 'utilities/ripple', but no scss file with that name exists, leading to compilation errors.

**Comment by djibe** [comment]
Hi. Thx for report.
Fixed in latest commit.
Sorry for that. My SSD crashed and I'm reinstalling my environment.
Don't hesitate to reopen Issue if necessary
