### ISSUE TITLE
Switch and Checkbox sizes

### ISSUE THREAD

**Issue by stsrki** [djibe/material#12]
Hi, any chance you might consider adding support for `sm` and `lg` sizes for Switch, Checkbox and Radio component? Other input components already have it and I think this could be a nice feature to have.

**Comment by djibe** [comment]
Hi, do you mean their Comfortable and Compact versions ?
https://material.io/design/layout/applying-density.html#components

Switch has no density guideline isn't it ?

**Comment by djibe** [comment]
Hi, do you confirm my previous message ?

**Comment by stsrki** [comment]
I'm really sorry, I was in a hurry when you sent last message that I forgot it later.

Anyways, I was thinking something like this:

- https://mdbootstrap.com/snippets/jquery/mdbootstrap/820849#css-tab-view
- https://stackoverflow.com/questions/55593229/increasing-the-size-of-a-bootstrap-checkbox

I know material design by default doesn't have that feature for check and switch, but it would be good to have since almost all other inputs already have it.

**Comment by djibe** [comment]
Hi. Thx for your feedback.
I won't introduce it now as its is neither in BS4 or MD. Maybe if BS5 does it.
It is not the vision of Material UI to introduce every component and I am not a fan of MDBootstrap which solds the work made by others (JS plugins +++)
You can feel free to create a Gist.

You can reopen Issue if you think it is important.
You can challenge iOS and MD designers if you want too.

Have a good summer and thx for your support.
