### ISSUE TITLE
Material Design for datatable.net Component

### ISSUE THREAD

**Issue by MROALI** [djibe/material#16]
Hello, 
Any native support for [https://datatables.net/](url) is on the roadmap ? 

For example implementing : 
https://codepen.io/tmpmosisili/pen/VEjzoM

Thank you in advance

**Comment by djibe** [comment]
Hi, I did one thème !

Like Select2, I'll do it in early september.
See you

**Comment by MROALI** [comment]
thankyou  :)

**Comment by MROALI** [comment]
Where can i find documentation for the plugins and for theme select2 and datatable.net ?

**Comment by djibe** [comment]
Hi, https://select2.org/ and https://www.datatables.net/

I'm working on Material UI doc

**Comment by MROALI** [comment]
> Hi, https://select2.org/ and https://www.datatables.net/
> 
> I'm working on Material UI doc

Where will be the location of the material UI Plugins doc ?

**Comment by djibe** [comment]
Below components, there will be a new section
![Screen Shot 09-07-20 at 12 30 PM](https://user-images.githubusercontent.com/13089414/92378353-f8d41300-f105-11ea-9b4a-bd6d4ac29c56.PNG)

**Comment by MROALI** [comment]
You didn't put the plugins documentation in the documentation website yet ? 
https://djibe.github.io/material/

**Comment by djibe** [comment]
Hi.
Not yet.
I am thinking about how to present it.

Build a second CSS file for plugins ?
Or build one single large file with plugins ?

**Comment by MROALI** [comment]
I think that depends of the size of the file, if it's not so heavy.. Keep it in one file which will be easier for use and prevent more than call from the navigator to load the file.

**Comment by MROALI** [comment]
Hello djibe thanks for the good work. 

Any idea when your will include the material design for the datatable.net in the source ? 

Best regards

**Comment by djibe** [comment]
Hi, you may try this WIP
[datatables-material.zip](https://github.com/djibe/material/files/5393397/datatables-material.zip)

**Comment by MROALI** [comment]
Thank you for the file. I tested it (remove the datatable file and added your file..).
There is somebug visible bug like the position of the paginate_button : 
![image](https://user-images.githubusercontent.com/22939696/96702144-c0288a00-1391-11eb-92d0-9970bfa6c7c0.png)
Also for example the searchbar is not showing so well : 
![image](https://user-images.githubusercontent.com/22939696/96702408-01209e80-1392-11eb-8b21-18306f2b7461.png)

do you have any new version to share ?

**Comment by djibe** [comment]
Hi.
I'll try to fix it in next weeks.
Overwhelmed right now

**Comment by djibe** [comment]
@MROALI  I'm on it right now

**Comment by djibe** [comment]
@MROALI What do you think of this ?

[datatables.zip](https://github.com/djibe/material/files/5433903/datatables.zip)

Compared to this https://material.io/components/data-tables#anatomy

**Comment by djibe** [comment]
Hi @MROALI , I will release it in the next version next weekend.

**Comment by MROALI** [comment]
> @MROALI What do you think of this ?
> 
> [datatables.zip](https://github.com/djibe/material/files/5433903/datatables.zip)
> 
> Compared to this https://material.io/components/data-tables#anatomy

Thankyou for the new version :  

Do i need to set datatable language  $.extend($.fn.dataTable.defaults, {  as u did in the sample ? Or just including the css file ?

Another question, does reponsive plugins will still working using your css ?

**Comment by djibe** [comment]
Hi, latest source is in master.
Use same config as previously.
Responsive is working, and better in the last commits

**Comment by MROALI** [comment]
I tested lastest version in master : 
1 - search box not showing so well  : 
![image](https://user-images.githubusercontent.com/22939696/97725710-c83da380-1ace-11eb-9ebe-037139a1911a.png)
2 - the footer section  also next and prévious are still visislbe 
![image](https://user-images.githubusercontent.com/22939696/97727550-d55b9200-1ad0-11eb-85ad-535129dec72f.png)

3- Sort Icon not showing in first colunm...

4- Select item count par page also : 
![image](https://user-images.githubusercontent.com/22939696/97727703-fd4af580-1ad0-11eb-9791-6c3672011d24.png)

NB : in my datatable i am overriding language to translate it.

"sProcessing":     "Traitement en cours...",
	"sSearch":         "Rechercher&nbsp;:",
    "sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
	"sInfo":           "Affichage de l'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
	"sInfoEmpty":      "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
	"sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
	"sInfoPostFix":    "",
	"sLoadingRecords": "Chargement en cours...",
    "sZeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
	"sEmptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
	"oPaginate": {
		"sFirst":      "Premier",
		"sPrevious":   "Pr&eacute;c&eacute;dent",
		"sNext":       "Suivant",
		"sLast":       "Dernier"
	},
	"oAria": {
		"sSortAscending":  ": activer pour trier la colonne par ordre croissant",
		"sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
	},
	"select": {
        	"rows": {
         		_: "%d lignes séléctionnées",
         		0: "Aucune ligne séléctionnée",
        		1: "1 ligne séléctionnée"
        	}  
	}
  };

I tested without it and still not working so well..

**Comment by djibe** [comment]
Yes you are using my old defaults.
I will release the final version this weekend

**Comment by djibe** [comment]
Hi,
I finished writing doc for DataTables.

Everything is in Master branch and I release new version tomorrow.

Here is the doc you need to move forward.

[DataTables.zip](https://github.com/djibe/material/files/5471800/DataTables.zip)

PS. Are you French ?

**Comment by MROALI** [comment]
> Hi,
> I finished writing doc for DataTables.
> 
> Everything is in Master branch and I release new version tomorrow.
> 
> Here is the doc you need to move forward.
> 
> [DataTables.zip](https://github.com/djibe/material/files/5471800/DataTables.zip)
> 
> PS. Are you French ?

Hello,
i am waiting your new version for today :). 
yes i am french :)

**Comment by djibe** [comment]
Hi,
I am writing Dark theme early version and then I release.

**Comment by djibe** [comment]
Argh je galère avec Firefox ... (après avoir galéré en JS pour la demo)

**Comment by MROALI** [comment]
Quel genre de problème ?  CSS ou JS ?

**Comment by djibe** [comment]
Here it is https://djibe.github.io/material/docs/4.5/plugins/datatables/

Firefox a du mal à comprendre qu'un background est blanc par héritage. Donc l'inversion de couleur avec le dark-theme ne fonctionne pas
