### ISSUE TITLE
Toasts dont work with Bootstrap Native (easy-fix)

### ISSUE THREAD

**Issue by justlevine** [djibe/material#18]
Hey,

Just noticed that toasts/snackbars arent working with [Bootstrap Native](https://github.com/thednp/bootstrap.native/issues/387). 

The reason is that the [`transition` property is on `.show`, instead of on `.toast`.](https://github.com/djibe/material/blob/master/assets/scss/material/_snackbars.scss#L41)

Is there a way to move this around?

PS: unrelated, but also noticed that in [boostrap](https://github.com/twbs/bootstrap/blob/v4.2.0/scss/_toasts.scss#L17), `.showing` has an `opacity:1`, but here it's set to 0. Is there a reason for that, or can that be fixed for parity?

**Comment by djibe** [comment]
Hi.
I'll try to see what I can do.

**Comment by djibe** [comment]
Hi @justlevine .
Thx to you I fixed it in master right now: https://github.com/djibe/material/commit/e006880ff45c8dccf1d6755c2a5e2234ae672a8b#diff-d56067c4a1d9bfcc739868f78b66065219dd45512944ecbe953bdbbbd5e0a184
I'll update auto-sizing soon.
Will be in next release.

**Comment by djibe** [comment]
Hi, fixed in 4.5.3
