### ISSUE TITLE
Method closest not available in IE

### ISSUE THREAD

**Issue by lgemeinhardt** [djibe/material#22]
IE 11 shows the following error (while clicking buttons like https://djibe.github.io/material/docs/4.6/material/buttons/):

SCRIPT438: Object doesn't support property or method 'closest'
ripplet.js (26,11)

**Comment by tbuyle** [comment]
On the other hand, Microsoft itself will not support IE11 in their own online app anymore (Teams since 2020-11-30 and O365 as of 2021-08-17).

**Comment by djibe** [comment]
Hi,
I'll work on it tomorrow.

**Comment by djibe** [comment]
Gosh,
I reworked the rollup.config.js for days but still no polyfills for IE10.

It looks like I have to try with: @babel/plugin-transform-runtime

If you can try this with latest commits.
https://github.com/djibe/material/blob/master/build/rollup.config.js

Thanks

**Comment by djibe** [comment]
Fixed in latest commit.
Use material.min.js from github.

Babel doesn't polyfill DOM methods like closest().
I had to import a specific polyfill.

**Comment by lgemeinhardt** [comment]
Looks good for me (I will close my PR) ... 
Thank you very much!
