### ISSUE TITLE
IE11 does not show material icons

### ISSUE THREAD

**Issue by lgemeinhardt** [djibe/material#24]
IE11 does not show material icons, because material font is included via var (not supported in IE11)

Example - https://djibe.github.io/material/docs/4.6/components/breadcrumb/ is renderd like: 
Home chevron_right Library

**Comment by djibe** [comment]
Fixed in https://github.com/djibe/material/commit/bc70a5fdc941df13d279293754b4400637f8e619

Thanks a lot !
