### ISSUE TITLE
Cannot type in input field of type text in modal

### ISSUE THREAD

**Issue by dipan66** [djibe/material#26]
I created a standard modal with a text input field.
   
I used `$("#searchmodal").modal("show")` from a nav drawer link click event to render the modal. It renders fine - but I just cant seem to be able to click on the input box and type anything. Also, every time I click on the input box, I get the following jquery error

Uncaught InternalError: too much recursion
    jQuery 3
    _enforceFocus nav-drawer.js:158
    jQuery 5
    _enforceFocus modal.js:326
    dispatch jQuery

What can I be doing wrong here? Should the modal and nav drawer not be open at the same time?

**Comment by dipan66** [comment]
Ah well - yes - nav drawer and modal cant be open at the same time. 
Closing the issue since this is obviously a BS4 limitation and nothing to do with the excellent framework provided by @djibe

**Comment by djibe** [comment]
Hi, very good news :D

Every bug report is a good thing.
Thanks for using this work.
