### ISSUE TITLE
Datatable language Configuration

### ISSUE THREAD

**Issue by MROALI** [djibe/material#27]
Hello,

I hope that everything is good for you.  In the documentation for datatable plugin it's better to replace _MAX_ with _TOTAL_ in the info property in the language object. => By using _TOTAL_ we show the total filtered rows and not the Max element present in the table.
https://djibe.github.io/material/docs/4.6/plugins/datatables/

info: '_START_-_END_ of _MAX_'  => info: '_START_-_END_ of _TOTAL_',

**Comment by djibe** [comment]
Hi, thanks a lot !
Fixed in b00a6a39
