### ISSUE TITLE
Bump Effect during tab Switch

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#28]
![image](https://user-images.githubusercontent.com/31451584/111962633-8d3d1a80-8b18-11eb-8d5f-cd843e7a872b.png)

During tab switch when the background is dark why the bump effect takes place it's adding a bad feel to UI, it feels like the icon is loading while only the color is changing.

Is there any way of tackling this?

**Comment by djibe** [comment]
Hi,

I'm testing the demo and I'm not sure of understanding your problem.

Sorry for that.
Can you be more precise ?

**Comment by gaurav2103** [comment]
> Hi,
> 
> I'm testing the demo and I'm not sure of understanding your problem.
> 
> Sorry for that.
> Can you be more precise ?

**Comment by gaurav2103** [comment]
@djibe i have changed the primary color to teal in material.min.css and on active nav to yellow now when i switch the tab it appears to be flicker because of the change of color. The Same you can see in the above screenshot example.

**Comment by gaurav2103** [comment]
@djibe  if u will go to the mentioned example just switch the tab and watch carefully the tab icon appears to flicker because of change of color can we avoid it somehow?

**Comment by djibe** [comment]
Hi, have you a gif or video ?

Did you recompile whole SASS with your new theme colors ?

**Comment by gaurav2103** [comment]
https://codepen.io/shukla2103/pen/OJNqyeE?editors=1010

please refer the penned code while i switch tab the icon appears to  blink

**Comment by gaurav2103** [comment]
@djibe  when i click on different  tab it changes to blue then white coz of this it appears to blink.

**Comment by djibe** [comment]
Hi,
Fixed in master.
You can use git clone to fetch latest sources

Thanks a lot for your report

**Comment by gaurav2103** [comment]
@djibe I am using it by downloading the dist.zip and importing it into vanilla js will the latest download will be able to resolve this?
