### ISSUE TITLE
Spiners are not working 

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#29]
@djibe Spinners are not working i think can you please look into the issue.
Below is the codepen link:
https://codepen.io/shukla2103/pen/VwPYZma

**Comment by djibe** [comment]
Hi, documentation and your fiddle have spinners working.

You may have prefers-reduced-motion set.

**Comment by gaurav2103** [comment]
@djibe don't have any idea about it can you please help

**Comment by djibe** [comment]
Hi, have you tried another web browser (Firefox, Edge) ?
Check your developer options and look for prefers-motion-reduced item.

Your fiddle renders like this on my PC
![default](https://user-images.githubusercontent.com/13089414/112189070-e9c93400-8c03-11eb-9ff2-a2ad8b51ae16.gif)

**Comment by gaurav2103** [comment]
@djibe thanks i turned on the the show animations options in my windows it is working now
