### ISSUE TITLE
Extra Large Modal and Large Modal have same size

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#30]
@djibe I am using the extra-large modal but its size seems to be the same as the large one could you please look into the issue

**Comment by djibe** [comment]
Hi,

true, I'll look into it.

**Comment by djibe** [comment]
Hi,
modal-xl is now Full-screen dialog: https://material.io/components/dialogs#full-screen-dialog
Thanks for your report.
Doc is updated in source but not yet online.
You can use latest sources to fix it
