### ISSUE TITLE
Not able  to change the  background color in steppers

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#32]
![image](https://user-images.githubusercontent.com/31451584/113289411-ce4ddf80-930d-11eb-9bce-235743edf99d.png)

I am not able to change the background color is it some issue or i am using the wrong way

**Comment by gaurav2103** [comment]
The color white is not changing

**Comment by tbuyle** [comment]
From the screencap it looks like you are changing the background of your _body_ or another container element.

Stepper have their own styling, including a backround color. these are set in https://github.com/djibe/material/blob/master/assets/scss/material/_stepper.scss where we can see that the variable $stepper-bg is used.

If you use SASS, you can change that variable. If not, you can set a new css rule applied to the .stepper class to change the background.

**Comment by djibe** [comment]
Hi,

thanks @tbuyle for your help.

Steppers have their own background because as many components for some themes they might need a proper dedicated background (ie Dark mode: greyish and not dark).
A transparent background would cause a failing UX design.
