### ISSUE TITLE
Scrollbar for Select

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#34]
![image](https://user-images.githubusercontent.com/31451584/113999881-158d2080-9878-11eb-9eba-377e8c0dc95a.png)
  Can I change the scrollbar to this type?

![image](https://user-images.githubusercontent.com/31451584/113999989-30f82b80-9878-11eb-8d04-22d7efcd9c29.png)
 the second scrollbar is coming for the web when I use the material but not for selection. is it possible to achieve?

**Comment by gaurav2103** [comment]
and also how could I control the number of options to be shown in the select dropdown.
Suppose i want 8 options  to shown and for rest scroll bar come

**Comment by tbuyle** [comment]
Typically, how select options are displayed depends on the browser and device. This is thus not directly styled by Material.

However, if you want more control on the selects and their options, Material integrates well with Select2 jquery plugin :  https://djibe.github.io/material/docs/4.6/plugins/select-select2/

**Comment by djibe** [comment]
Hi @shukla2103 , which component are you using ?
Normaly stylebars are always cool using Chrome or Firefox.
HTML5 doesn't offer the ability to choose menu's dropdown size.

**Comment by djibe** [comment]
Thanks @tbuyle for your support.

**Comment by gaurav2103** [comment]
@djibe I am using text field- select component with floating label
