### ISSUE TITLE
Change modal box shadow 

### ISSUE THREAD

**Issue by Posandu** [djibe/material#37]
Please can you change the box shadow of the modal component to this
 ```
.modal-content {
    border-radius: 2px;
    background-color: #ffffff;
    box-shadow: 0px 11px 15px -7px rgba(0, 0, 0, 0.2),0px 24px 38px 3px rgba(0, 0, 0, 0.14),0px 9px 46px 8px rgba(0,0,0,.12);
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    outline: 0;
    pointer-events: auto;
    position: relative;
    vertical-align: baseline;
    width: 100%;
}
```

Before
<img src="https://i.ibb.co/ph3pft3/Screenshot-2021-04-24-Screenshot-1.png">
After adding the code
<img src="https://i.ibb.co/yVyzRpK/Screenshot-2021-04-24-Screenshot.png">
The 2nd one is the material design modal. See it https://material.io/inline-tools/dialog/

**Comment by djibe** [comment]
Hi, as stated in _dialog.scss, shadows come from Material Components for the web: https://material-components.github.io/material-components-web-catalog/#/component/elevation

**Comment by Posandu** [comment]
Can you add the box shadow that is officially in material design ?

**Comment by djibe** [comment]
OK I will.
Can you provide me links to material.io components to check all Components shadows ?
![Screen Shot 04-24-21 at 05 03 PM](https://user-images.githubusercontent.com/13089414/115963387-5a26e600-a51f-11eb-82c8-ed070d4993db.PNG)

**Comment by Posandu** [comment]
Thanks for responding , You can see all the components <a href="https://material-components.github.io/material-components-web-catalog/#/">Here</a>

**Comment by djibe** [comment]
Thx I know :D

**Comment by Posandu** [comment]
Did you try adding this to your search ? Created by Google https://programmablesearchengine.google.com/cse/create/new

**Comment by Posandu** [comment]
closing the issue thanks !

**Comment by djibe** [comment]
Hi, you can keep it open.
I will change the shadows tonight.
Then I'll work on bringing back the search menu.

**Comment by Tronic247** [comment]
_You are such a nice person_ & **this is the best framework** comparing for other frameworks like[ Mdbootstrap](https://mdbootstrap.com/). If you need help with styling that search engine I will help with some code.

**Comment by djibe** [comment]
Well, didn't find any diffrence between my modals and Google's ones.

```
.modal-content {
    box-shadow: 0 24px 38px 3px rgb(0 0 0 / 14%), 0 9px 46px 8px rgb(0 0 0 / 12%), 0 11px 15px -7px rgb(0 0 0 / 20%);
}
```

and

```
.mdc-dialog__surface {
    box-shadow: 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0,0,0,.12);
}
```
