### ISSUE TITLE
How to change the color of a text field ?

### ISSUE THREAD

**Issue by Posandu** [djibe/material#38]

**Comment by djibe** [comment]
Hi, cany ou be more precise ?

Color of text ? Placeholder ? Border ? Background ?

**Comment by Posandu** [comment]
Sorry for no information , I need to change Color of text , Placeholder and Border

**Comment by djibe** [comment]
Hi,

you can override variables: $textfield-color, $textfield-placeholder-color and $textfield-border-color / $textfield-border-color-hover / $textfield-border-color-focus

See assets/scss/variables/_variable-material.scss

**Comment by Posandu** [comment]
okay
