### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by r0hin** [djibe/material#4]
Hi,
had some potential feature requests:

- Custom select something like [this](https://material-components.github.io/material-components-web-catalog/#/component/select)
- list in the readme or someplace listing the changes from the original fork.
- Ripple effect
- In the text fields, add a ripple to the underline like [this](https://material-components.github.io/material-components-web-catalog/#/component/text-field)
- Closing modal animation like in the [original repo](https://daemonite.github.io/material/docs/4.1/components/modal/#modal-components)

There are just some things I think would be cool if added here. Just kinda to make it more like google's version.

Thanks!

**Comment by djibe** [comment]
Hi, thx for your requests.
I share your wishes and will try to do my best (even though I am no developer at all).

I'll start with ripple effect.

For the closing animation of Dialogs, I don't think it is a good idea because Material components don't have this effect ; 

- https://material-components.github.io/material-components-web-catalog/#/component/dialog
- https://material.io/components/dialogs#behavior

**Comment by r0hin** [comment]
Hi, thanks for trying!

I'm also not a developer, but I suppose I have some experience and could contribute some things.
As for the modal, I was thinking like a fade effect like the examples you sent.

I would recommend implementing something like [Fians Waves Effect](https://github.com/fians/Waves) as it looks pretty clean and I've used it before.

**Comment by djibe** [comment]
I'm on it at this exact moment :D

**Comment by r0hin** [comment]
Awesome thanks so much. I guess while I'm here I should mention some things like tabs which aren't present in the forked version but are there in the original repo.

**Edit:** Found out I was being dumb, tabs exist!

**Comment by djibe** [comment]
These tabs ? 

https://djibe.github.io/material/docs/4.4/material/tabs/

**Comment by r0hin** [comment]
omg yes... the search feature, i thought it was just no results for tabs !!

**Comment by djibe** [comment]
Search field is disabled. Dependant on algolia.
I'll have to fix it too.

Look at every Material component and tell me what you think.

**Comment by r0hin** [comment]
I've pretty inexperienced I would say but here's my feedback:

- Buttons, cards, chips, progress, shadows, lists, and data tables are remarkably similar to google's specifications, missing waves obviously
- Dialogs missing a fade imo
- Menu & Dropdown animations could be tweaked kind of like [material components version](https://material-components.github.io/material-components-web-catalog/#/component/menu)
- The drawers could also be tweaked ie: drawer header should be same color & subtitles smaller.
- Snackbars are good, but I would never use them when I can just call `Snackbar.show({text: "Text here"})` with SnackbarJS. Maybe add some functionality to call a snackbar without having the actual snackbar div element. Also, support for multiple snackbars at once.
- Tabs are great I love the fade
- Forms: I think a lot should be changed here such as the ripple on the line like i mentioned before,  a custom select menu 

That's pretty much all the feedback I have a lot of it is just personal preference of what I think would look good. Pretty excited on working on this w/ u. gonna try contributing my 2 cents to the code sometime :)

**Comment by djibe** [comment]
Good news,
I did line ripple and button ripple yesterday.

Now I have to integrate it nicely.

**Comment by djibe** [comment]
You can test line ripples here : https://djibe.github.io/material/docs/4.4/material/text-fields/

**Comment by djibe** [comment]
You can test button ripples here : https://codepen.io/djibe89/pen/oNjMjQx

**Comment by r0hin** [comment]
Ripples are great!!
Nice to see this quick progress

**Comment by r0hin** [comment]
I imagine this will be applied to all the other parts of UIs: ie the dropdown menus, tabs, selects.., right?

**Comment by djibe** [comment]
Yep

**Comment by r0hin** [comment]
Hey, noticed a small bug in the demo on codepen. If you click directly on the icon in the button, the waves effect doesn't show.

**Comment by djibe** [comment]
Yep I noticed, I'm on it

**Comment by djibe** [comment]
Fixed by luncheon https://codepen.io/luncheon/pen/zYvLNvM

**Comment by r0hin** [comment]
looks great!

**Comment by r0hin** [comment]
I think I got git contributing figured out :D was wondering if you need any help with any components or if anything is unfinished?

**Comment by djibe** [comment]
Hey ! Git is good :D

I had troubles with switch component.
It is the last one missing I think.
I enhenced Buttons + icons yesterday (Fontawesome 4 + 5 + svg support)

**Comment by r0hin** [comment]
Alright, I have it cloned and everything, how do you usually do development?

**Comment by djibe** [comment]
I usually have an HTML page in a folder.
And copy latest material.css and material.map.css in it.

Then I customize component using <style> in HTML header.
I test in various conditions.

And then integrate code in scss.
You can just edit CSS for the Switch component and send it to me.
I'll do the rest and credit you.

Thx a lot.
Good tutos on Udemy for Git, Github and SASS/SCSS.

**Comment by r0hin** [comment]
Here's switch
https://pastebin.com/raw/Ccqt0ht6

**Comment by djibe** [comment]
Hey, thx.

looks like you used Daemonite HTML markup that dates back to Bootstrap having no switches.

Can you do it for Bootstrap's Switch ?
https://djibe.github.io/material/docs/4.4/components/forms/#switches

Thks.
I won't do CSS this weekend.
See you next week.

**Comment by r0hin** [comment]
Got it :D.
Sorry for late reply (didn't get the edit notification)

**Comment by r0hin** [comment]
I'm not sure how to solve this as the ::before is the onclick wave thing and that's whats used as the slider in regular bootstrap

**Comment by djibe** [comment]
@rohinarya12 Let it go.
I've fixed it. Will be in next release when I have solved ripple default config.

(gif is not perfectly fluid but component is)

![switch](https://user-images.githubusercontent.com/13089414/83009648-5a6ce780-a017-11ea-9578-67494356813f.gif)

**Comment by r0hin** [comment]
Really? You got it?! I tried for a while, couldn't figure it out :O

**Comment by djibe** [comment]
I updated code in repo.
See _selection-control.scss.
Just setting 2 box-shadows on switch handle (original + shadow when input.custom-control-input is :focused)

**Comment by djibe** [comment]
Brand new release : https://djibe.github.io/material/
Switches + button ripples

**Comment by r0hin** [comment]
Looks great and the library you used is really good :D. I’m sure you are aware but the waves aren’t yet implemented across the components such as dropdown items and tabs. 

Good stuff though

**Comment by djibe** [comment]
I'm on it :D
