### ISSUE TITLE
Card overflow is messing with dropdown menu

### ISSUE THREAD

**Issue by stsrki** [djibe/material#40]
If a dropdown is placed inside of card element it will be hidden when it is too large

![image](https://user-images.githubusercontent.com/900302/117205957-8df0ee00-adf2-11eb-902a-9d46ffaa924c.png)

When I disable overflow it seems to work

```css
.card {
    overflow: initial;
}
```

![image](https://user-images.githubusercontent.com/900302/117206118-baa50580-adf2-11eb-8817-27e22ba5040d.png)

Also, I was comparing Material with regular Bootstrap and in Bootstrap, there is no `overflow ` attribute on `.card` element.

**Comment by djibe** [comment]
Hi, fixed in latest commit.
Thanks a lot for your debugging !

By the way, if you are looking for an Autocomplete, have you tried Select2 from the Plugins menu ?

**Comment by stsrki** [comment]
Thanks!

Yes I saw Select2 plugin and I have a plan to implement it as an extension for Blazorise at some point. But I always prefer to have native Blazor components instead of depending too mich on javascript.
