### ISSUE TITLE
Selected Index overlapping with label

### ISSUE THREAD

**Issue by gaurav2103** [djibe/material#41]
![image](https://user-images.githubusercontent.com/31451584/121509218-0a837780-ca04-11eb-9d07-35ca575a0b15.png)

The above image overlaps with the label when its attribute is kept as selected.

I want like the below image:
![image](https://user-images.githubusercontent.com/31451584/121509722-909fbe00-ca04-11eb-8a94-1383eb648deb.png)
 Please help.

**Comment by djibe** [comment]
Hi, you probably didn't initialize floating labels:
`$('.floating-label .custom-select, .floating-label .form-control').floatinglabel();`

**Comment by gaurav2103** [comment]
@djibe I have used the floating-label class with select but the label is overlapping.
Actually i am loading the values in the select box onpageload with one selected option.

**Comment by djibe** [comment]
Hi, you see first option must be empty

https://djibe.github.io/material/docs/4.6/material/text-fields/#demo-for-floating-label-text-fields
