### ISSUE TITLE
Add material design select with floating label and smooth transition when closing and opening

### ISSUE THREAD

**Issue by Posandu** [djibe/material#44]
You get the idea compare https://djibe.github.io/material/docs/4.6/plugins/select-select2/ vs https://material-components.github.io/material-components-web-catalog/#/component/select

**Comment by djibe** [comment]
Hi,
I won't be able to do this.
But I'll merge your PR if needed.
Thanks

**Comment by Posandu** [comment]
@djibe Okay then bye bye issue , +100 for developing framework , -1 for no floating labels  :( !!

**Comment by djibe** [comment]
Hello,
I'll try to tweak Select2. Or you may know a better alternative ?

**Comment by Posandu** [comment]
Tada !! 
https://jsfiddle.net/nsdpayk6/

**Comment by djibe** [comment]
Awesome.
I have to figure out how to compile docs from master to gh-pages branch.

**Comment by Tronic247** [comment]
One thing more ... If this helped a lot please subscribe my Youtube Channel https://www.youtube.com/tronic247?sub_conformation=1 , thanks

**Comment by Posandu** [comment]
@djibe Also can you replace the ripple effect like this https://jsfiddle.net/fhcxystv/

**Comment by Tronic247** [comment]
@djibe ?

**Comment by djibe** [comment]
Yes I'm here :D
But i have a newborn ...

**Comment by Tronic247** [comment]
Sorry :(

**Comment by djibe** [comment]
I'll do it ... when I have some time.
