### ISSUE TITLE
Search Doesen't work at all 

### ISSUE THREAD

**Issue by Posandu** [djibe/material#45]
![image](https://user-images.githubusercontent.com/76736580/123102707-f6ebfe00-d452-11eb-9373-115b0d1a3947.png)

**Comment by djibe** [comment]
Hi, yes I saw it yesterday.
I looked at the _docsearch_ config and can't find why it doesn't work.

**Comment by Tronic247** [comment]
Check browser console when searching 
![image](https://user-images.githubusercontent.com/76736580/123451958-96e48b80-d5fb-11eb-95b5-778fc5853fa8.png)

**Comment by djibe** [comment]
Hi, saw it earlier, even though I regenerated the API key.
docsearch is not easy to configure...

**Comment by Tronic247** [comment]
Then remove the search

**Comment by Posandu** [comment]
@djibe I think you should remove this search until things are stable

**Comment by djibe** [comment]
I will. Thx

**Comment by Tronic247** [comment]
Taking longer than usual ;(

**Comment by djibe** [comment]
Fixed.
Docsearch HOWTO is really not clear.
Had to edit search config from their repository.
