### ISSUE TITLE
dropdown link not working

### ISSUE THREAD

**Issue by Duplore** [djibe/material#48]
Having this issue with the linking in the dropdown-menu

https://stackoverflow.com/questions/15050095/a-link-not-working-by-clicking-only-work-by-open-link-in-new-tab-command

**Comment by djibe** [comment]
Hi, I don't see how this JS bug relates to this CSS library.

**Comment by Duplore** [comment]
links do not work in dropdown.

**Comment by Duplore** [comment]
I can't seem to find an issue on why it's doing that, also this issue occurs in your docs for dropdowns so its not my side.

**Comment by Duplore** [comment]
Links do not work for dropdown items nor other links that's not related to the class 'dropdown-item'

**Comment by djibe** [comment]
Hi @Duplore , the docs.js file blocks links default behaviour in the documentation.
It is intended to prevent weiird actions when playing in the documentation sandbox.
In your own projects, it won't be a problem.
I call material.min.js in my own projects and have no dropdown-item or dropdown links problems.
