### ISSUE TITLE
Any boilerplate code available

### ISSUE THREAD

**Issue by nitinmukesh** [djibe/material#50]
Hello,

I am new to web development and working on a free web application for users interested in Astrology which I already developed (a lot of new features to add) but now want to use some fancy components to rebuild the frontend.
https://rococo-beijinho-7c6afc.netlify.app/

Please does someone have a boilerplate code (with top bar, menu, etc) with djibe/material library to help me get started. I see a lot of components here which could be useful for me to start with.

**Comment by djibe** [comment]
Hi, the official site is built with default components: https://djibe.github.io/material/

Advanced components are available from the Material submenu.

**Comment by nitinmukesh** [comment]
Thank you
