### ISSUE TITLE
https://djibe.github.io/material/ doesnt load

### ISSUE THREAD

**Issue by GuiFV** [djibe/material#52]
When visiting the url https://djibe.github.io/material/ I get:

This site can’t provide a secure connection
djibe.github.io sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by djibe** [comment]
Hi, nothing from this sort with any of my 4 browsers (Firefox, Chrome, Edge, Brave).

**Comment by GuiFV** [comment]
Maybe its my connection then, because the error persists with brave, safary and edge (mac)

**Comment by GuiFV** [comment]
I VPN'nd to Netherlands and it worked (I am in UK)
